### ISSUE TITLE
Feature proposal: link Sentry issues to existing Redmine tasks

### ISSUE THREAD

**Issue by tonyo** [getsentry/sentry-redmine#3]
Our dev team find it convenient to be able to link Sentry issues to already created tasks on Redmine. A couple of use cases: 
- A bug was reported from a different source (clients, marketing/QA team), and the task was already created directly on Redmine.
- Several Sentry issues might be manifestations of a single bug/issue (hence, one Redmine task), and it makes sense to link all the issues to one task, and merging the Sentry issues is not always the best way.

The feature is already implemented and being used by our team, here are the changes: https://github.com/rev112/sentry-redmine/commit/5f2b84a140ac6a1ee0b9235d9bca45922b22be8d

If you would like to see this feature merged and/or you have better ideas how to implement this -- I'm open for feedback.

How it looks like (a user has to select the checkbox AND enter a task ID, to make it a bit more foolproof):

![sentry_link_existing](https://cloud.githubusercontent.com/assets/1120468/16179018/76fde3d0-3659-11e6-91d1-009022411754.jpg)

**Comment by zhangjianpinghik** [comment]
why i configure Redmine in sentry failed?
the error information:There was an issue authenticating with Redmine
my configuration is:
hosts:
https://redmine.junlins.site/projects/test
Key:
c7d656359b882xxx480cc7d5ada39c70b6538715

**Comment by zhangjianpinghik** [comment]
how you configure you redmine in sentry? i configured faild,but i do not know what is worng?
follow is my configuration:
hosts:
https://redmine.junlins.site/projects/test
Key:
c7d656359b882xxx480cc7d5ada39c70b6538715

**Comment by mattrobenolt** [comment]
Hey @zhangjianpinghik, I've edited your comments to remove the API Key you published. In the future, you should avoid doing that. :)

**Comment by zhangjianpinghik** [comment]
@mattrobenolt  ok thanks!

**Comment by tonyo** [comment]
@zhangjianpinghik I recommend you to create a new issue if you are still having issues with configuration. 
You can also try to interact with Redmine API via command-line tools like 'curl' first (see http://www.redmine.org/projects/redmine/wiki/Rest_Issues#Creating-an-issue), to make sure that Redmine doesn't wait for some required fields to create a new issue.

**Comment by tonyo** [comment]
@zhangjianpinghik ah, sorry, I've just noticed that you have done it already.

**Comment by mattrobenolt** [comment]
We should be able to do this after https://github.com/getsentry/sentry/pull/3495 is landed.

/cc @macqueen

**Comment by zhangjianpinghik** [comment]
@rev112  yes ,i resolved,thanks!

**Comment by tonyo** [comment]
@mattrobenolt Ok, cool, then let's leave this open until the new Sentry version with the link/unlink changes is out. I can make the required changes for `sentry-redmine` after that.

**Comment by tonyo** [comment]
Created a PR (#6).
