### ISSUE TITLE
configure redmine in sentry faild,please help what is wrong?

### ISSUE THREAD

**Issue by zhangjianpinghik** [getsentry/sentry-redmine#4]
why i configure Redmine in sentry failed?
the error information:There was an issue authenticating with Redmine
my configuration is:
hosts:
https://xxxxxxxxx/1111/1111
Key:
c7d656359b882xxx480xxxxx70b6538715

**Comment by zhangjianpinghik** [comment]
I have resolved

**Comment by mattrobenolt** [comment]
What was the issue?

**Comment by zhangjianpinghik** [comment]
@mattrobenolt the hosts url is not point to some some one project

**Comment by zhangjianpinghik** [comment]
@mattrobenolt i put  your a new request for sentry-redmine, pelase take into account 
https://github.com/getsentry/sentry/issues/3540
